name: beautyshare3
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  cloud_firestore:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^0.0.13


  flutter_staggered_grid_view: "^0.2.2"
  image_picker:
  firebase_storage:
  path_provider: ^0.4.1
  uuid: ^1.0.3
  image: ^2.0.4
  transparent_image: ^0.1.0
  english_words: ^3.1.4
  easy_alert: ^0.0.2
  flutter_swiper: ^1.1.4
  intl: ^0.15.7
  scoped_model: ^0.3.0











dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
   - images/lake.jpg
   - images/pavlova.jpg
   - main_image.png
   - eyelasj.png
   - 1.jpg
   - 2.jpg
   - 3.jpg
   - 4.jpg
   - 5.jpg
   - 6.jpg
   - 7.jpg
   - 8.jpg
   - 9.jpg
   - 10.jpg
   - 11.jpg
   - 12.jpg
   - 13.jpg
   - 14.jpg
   - 15.jpg
   - 16.jpg
   - 17.jpg
   - 18.jpg
   - 19.jpg
   - 20.jpg
   - 21.jpg
   - 22.jpg
   - 23.jpg
   - 24.jpg
   - 25.jpg
   - 26.jpg
   - 27.jpg
   - 29.jpg
   - 30.jpg
   - chesk.png
   - eyelasj.png
   - filter.png
   - home.png
   - lake.jpg
   - map.png
   - mypage.png
   - pavlova.jpg
   - promotion.png
   - review.png
   - review_black.png
   - backbutton.png
   - Loading_icon.gif
